[package]
name = "tiny_skia_rust_png"
version = "0.1.0"
edition = "2021"

[lib]
name = "tiny_skia_rust_png"
path = "src/lib.rs"
crate-type = ["staticlib", "rlib"]

[[bin]]
name = "tiny_skia_rust_png"
path = "src/main.rs"

[dependencies]
tiny-skia = "0.11.4"
